# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\"\xc0\x01\n\x07Payment\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x13\n\x0btotal_price\x18\x02 \x01(\x05\x12\x16\n\x0epayment_method\x18\x03 \x01(\t\x12\x12\n\npayment_id\x18\x04 \x01(\x05\x12\x19\n\x11payment_intent_id\x18\x05 \x01(\t\x12\x16\n\x0epayment_status\x18\x06 \x01(\t\x12\x19\n\x11remaining_balance\x18\x07 \x01(\x02\x12\x14\n\x0cis_completed\x18\x08 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PAYMENT._serialized_start=18
  _PAYMENT._serialized_end=210
# @@protoc_insertion_point(module_scope)
